name: Python package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        exclude:
          - os: 'ubuntu-22.04'
            python-version: '3.6'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install libxkbcommon-dev
        run: |
          sudo apt-get install libxkbcommon-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --ignore=E124,E302,E305,E722,E741,F841,W503 --show-source --statistics --max-line-length=127
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build ffi module
        run: |
          python setup.py build_ext --inplace
      - name: Test with pytest
        run: |
          pytest
